<a href="https://colab.research.google.com/github/Thiago383/Bibliotecas_Python/blob/main/Biblioteca_NumPy_Indexacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔎 Indexação e Fatiamento de Arrays com NumPy

Este notebook mostra como realizar operações de **indexação, fatiamento e comparações lógicas** em arrays NumPy de 1 e 2 dimensões.



## ✅ Indexação de Arrays 1D
Vamos criar um array de 1 dimensão com valores de 0 a 30, de 3 em 3:

In [ ]:
array = np.arange(0, 30, 3)
print(array)

## ✅ Acessando posições específicas

In [ ]:
# Acessa o elemento na posição 3
array[3]

# Acessa da posição 0 até a 2 (exclui a 2)
array[0:2]

# Acessa da primeira posição até a 5 (exclui a 5)
array[:5]

# Acessa da posição 2 até o final
array[2:]

# Acessa posições específicas: 0 e 5
array[[0, 5]]

array([ 0, 15])

## ✅ Modificando valores

In [ ]:
# Substitui os valores da posição 5 até o final por 100
array[5:] = 100

# Mostra o array modificado
print(array)

[  0   3   6   9  12 100 100 100 100 100]


## ✅ Indexação de Arrays 2D

Vamos criar uma matriz 5x10 com valores de 0 a 49:

In [ ]:
array_2d = np.arange(50).reshape(5, 10)
print(array_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## ✅ Fatiando matrizes

In [ ]:
# Linhas de 0 a 2 (exclui a linha 3)
array_2d[0:3]

# Linhas de 0 a 2, colunas de 0 a 2
array_2d[0:3, 0:3]

# Linhas de 0 a 2, colunas de 4 até o fim
array_2d[0:3, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

## ✅ Comparações Lógicas com Arrays

In [ ]:
# Mostra o array
print(array_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## ✅ Verificando condição simples

In [ ]:
# Retorna uma matriz booleana onde o valor é maior que 20
array_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
# Armazena a condição em uma variável
boleano = array_2d > 20

# Filtra os valores com base na condição
array_2d[boleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## ✅ Usando múltiplas condições

In [ ]:
# Verifica se os valores estão entre 20 e 30
np.logical_and(array_2d >= 20, array_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
# Armazena o resultado da comparação
boleano_01 = np.logical_and(array_2d >= 20, array_2d <= 30)

# Filtra os valores com base nas condições compostas
array_2d[boleano_01]