<a href="https://colab.research.google.com/github/Thiago383/Bibliotecas_Python/blob/main/Biblioteca_NumPy_Introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📦 Introdução ao NumPy

**NumPy** (Numerical Python) é um pacote fundamental para computação numérica em Python. Ele oferece suporte para arrays multidimensionais e diversas funções matemáticas de alto desempenho. Criado para ser eficiente e escalável, é amplamente utilizado em:

- Ciência de Dados
- Inteligência Artificial
- Engenharia
- E outras áreas que envolvem grandes volumes de dados numéricos


In [ ]:
# 📌 Importando o pacote
import numpy as np

## ✅ Criando Vetores e Arrays

In [ ]:
# Criando uma lista comum do Python
minha_lista = [1, 2, 3]

# Convertendo a lista em um array NumPy (vetor unidimensional)
vetor = np.array(minha_lista)
print(vetor)
# Saída: array([1, 2, 3])

[1 2 3]


In [ ]:
# Criando uma matriz bidimensional
minha_matriz = [[1, 2, 3], [4, 5, 6]]

# Convertendo a lista de listas em uma matriz NumPy
matriz = np.array(minha_matriz)
print(matriz)
# Saída:
# array([[1, 2, 3],
#        [4, 5, 6]])

[[1 2 3]
 [4 5 6]]


## ✅ Somando elementos

In [ ]:
# Soma simples usando a função nativa do Python
soma_lista = sum(minha_lista)
print(soma_lista)  # Saída: 6

6


In [ ]:
# Tentando somar a matriz (vai gerar erro com sum())
# sum(minha_matriz)  # ❌ Vai gerar erro!

# Correto: usar NumPy para somar os elementos da matriz
matriz_numpy = np.array(minha_matriz)
soma_matriz = np.sum(matriz_numpy)
print(soma_matriz)  # Saída: 21

21


## ✅ Gerando arrays com intervalos (função `arange`)

In [ ]:
# Array de 0 até 9
arr1 = np.arange(0, 10)
print(arr1)
# Saída: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Array de 0 até 998, com passo de 2
arr2 = np.arange(0, 1000, 2)
print(arr2[:10])  # Exibindo os primeiros 10 elementos

[ 0  2  4  6  8 10 12 14 16 18]


## ✅ Arrays com valores iguais

In [ ]:
# Matriz 3x5 preenchida com zeros
zeros = np.zeros((3, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Matriz 3x3x3 (tridimensional) preenchida com zeros
zeros_3d = np.zeros((3, 3, 3))
print(zeros_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# Matriz 3x5 preenchida com uns
uns = np.ones((3, 5))
print(uns)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Matriz 2x2 preenchida com valor específico (por exemplo: 7)
sete = np.full((2, 2), 7)
print(sete)

[[7 7]
 [7 7]]


##  Dicas

- `np.array()` → converte listas para arrays
- `np.sum()` → soma os elementos do array
- `np.arange(start, stop, step)` → cria sequência de números
- `np.zeros(shape)` → array com zeros
- `np.ones(shape)` → array com uns
- `np.full(shape, value)` → array com valor específico