<a href="https://colab.research.google.com/github/Thiago383/Bibliotecas_Python/blob/main/Biblioteca_NumPy_Operacoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ➕ Operações com NumPy e Arrays

Neste notebook vamos explorar **operações matemáticas básicas** utilizando arrays da biblioteca NumPy.


## ✅ Criação dos Arrays

In [ ]:
# Cria array1 com valores de 0 a 90, de 10 em 10
array1 = np.arange(0, 100, 10)

# Cria array2 com valores de 0 a 45, de 5 em 5
array2 = np.arange(0, 50, 5)

## ✅ Visualizando os Arrays

In [ ]:
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

Array 1:
[ 0 10 20 30 40 50 60 70 80 90]

Array 2:
[ 0  5 10 15 20 25 30 35 40 45]


## ✅ Operações Matemáticas com Arrays

Lembre-se: para realizar operações entre arrays, eles precisam ter o mesmo tamanho.

In [ ]:
# Soma dos elementos
print("Soma:")
print(array1 + array2)

# Subtração dos elementos
print("\nSubtração:")
print(array1 - array2)

# Multiplicação dos elementos
print("\nMultiplicação:")
print(array1 * array2)

# Divisão dos elementos
print("\nDivisão:")
print(array1 / array2)

Soma:
[  0  15  30  45  60  75  90 105 120 135]

Subtração:
[ 0  5 10 15 20 25 30 35 40 45]

Multiplicação:
[   0   50  200  450  800 1250 1800 2450 3200 4050]

Divisão:
[nan  2.  2.  2.  2.  2.  2.  2.  2.  2.]


<ipython-input-25-b45a4b7ead59>:15: RuntimeWarning: invalid value encountered in divide
  print(array1 / array2)
